package proyectofint1;

import java.awt.Color;

public class Embalajes extends javax.swing.JFrame {

    public Embalajes() {   
        setLocation(300, 100);
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jAncho = new javax.swing.JTextField();
        jAlto = new javax.swing.JTextField();
        jLargo = new javax.swing.JTextField();
        button1 = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jAncho.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jAncho.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jAnchoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jAnchoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jAnchoKeyTyped(evt);
            }
        });

        jAlto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAltoActionPerformed(evt);
            }
        });
        jAlto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jAltoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jAltoKeyReleased(evt);
            }
        });

        jLargo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLargoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jLargoKeyReleased(evt);
            }
        });

        button1.setBackground(new java.awt.Color(255, 255, 255));
        button1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button1.setLabel("Guardar");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveData(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));

        jLabel2.setText("Ancho");

        jLabel3.setText("Alto");

        jLabel4.setText("Largo");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("EMBALAJES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(189, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jAncho, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(66, 79, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jAlto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLargo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(93, 93, 93))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(196, 196, 196))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel5)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAncho, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAlto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLargo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jAncho.getAccessibleContext().setAccessibleName("Width");
        jLabel1.getAccessibleContext().setAccessibleName("Label5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveData(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveData
       
        if (jLargo.getText().equals("") || jAlto.getText().equals("") || jAncho.getText().equals("") ) {
            jLabel1.setText("Rellena todos los campos");
        }else {
             DatosEmbalajes d=new DatosEmbalajes();
             d.alto=Integer.parseInt(jAlto.getText());
             d.largo=Integer.parseInt(jLargo.getText());
             d.ancho=Integer.parseInt(jAncho.getText());
             d.EscribirFichero();
             jLabel1.setText("Añadido correctamente");
             jAlto.setText("");
             jLargo.setText("");
             jAncho.setText("");
             jLabel1.setForeground(Color.GREEN);
             
        }
          
    }//GEN-LAST:event_SaveData

    private void jAnchoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jAnchoKeyPressed
        
        int key=evt.getKeyCode();
        if ((key>=evt.VK_0 && key<=evt.VK_9) || key==evt.VK_BACK_SPACE) {
           jAncho.setEditable(true);
           jAncho.setBackground(Color.GREEN); 

        }else {
            jAncho.setEditable(false);
            jAncho.setBackground(Color.red);
            jLabel1.setText("Introduce sólo números");
        }
    }//GEN-LAST:event_jAnchoKeyPressed

    private void jAltoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAltoActionPerformed
        
    }//GEN-LAST:event_jAltoActionPerformed

    private void jAltoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jAltoKeyPressed
        int key=evt.getKeyCode();
        if ((key>=evt.VK_0 && key<=evt.VK_9) || key==evt.VK_BACK_SPACE) {
           jAlto.setEditable(true);
           jAlto.setBackground(Color.GREEN); 
           jLabel1.setText("");
        }else {
            jAlto.setEditable(false);
            jAlto.setBackground(Color.red);
            jLabel1.setText("Introduce sólo números");
        }
    }//GEN-LAST:event_jAltoKeyPressed

    private void jLargoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLargoKeyPressed
         int key=evt.getKeyCode();
        if ((key>=evt.VK_0 && key<=evt.VK_9) || key==evt.VK_BACK_SPACE) {
           jLargo.setEditable(true);
           jLargo.setBackground(Color.GREEN); 
           jLabel1.setText("");
        }else {
            jLargo.setEditable(false);
            jLargo.setBackground(Color.red);
            jLabel1.setText("Introduce sólo números");
        }
    }//GEN-LAST:event_jLargoKeyPressed

    private void jAnchoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jAnchoKeyTyped
        
    }//GEN-LAST:event_jAnchoKeyTyped

    private void jAnchoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jAnchoKeyReleased
           int vl=1;
           try {
           vl=Integer.parseInt(jAncho.getText());
           }catch (Exception e){
               
           }
            
           if(vl>0 && vl<=30){
               jAncho.setBackground(Color.GREEN);
               jLabel1.setText("");
           }else {  
               jAncho.setBackground(Color.red);
               jLabel1.setText("El límite es 30");
           }       
    }//GEN-LAST:event_jAnchoKeyReleased

    private void jAltoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jAltoKeyReleased
       int vl=1;
           try {
           vl=Integer.parseInt(jAlto.getText());
           }catch (Exception e){
               
           }
            
           if(vl>0 && vl<=30) {
               jAlto.setBackground(Color.GREEN);
               jLabel1.setText("");
           }
           else {   
               jAlto.setBackground(Color.red);
               jLabel1.setText("El límite es 30");
           }
    }//GEN-LAST:event_jAltoKeyReleased

    private void jLargoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLargoKeyReleased
       int vl=1;
           try {
           vl=Integer.parseInt(jLargo.getText());
           }catch (Exception e){
               
           }
            
           if(vl>0 && vl<=40){
               jLargo.setBackground(Color.GREEN);
               jLabel1.setText("");
           }
           else {   
               jLargo.setBackground(Color.red);
               jLabel1.setText("El límite es 40");
           } 
    }//GEN-LAST:event_jLargoKeyReleased
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Embalajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Embalajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Embalajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Embalajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Embalajes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private javax.swing.JTextField jAlto;
    private javax.swing.JTextField jAncho;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jLargo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
