package proyectofint1;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public class Envios extends javax.swing.JFrame {

    private String id="";
    public Envios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private int Clicks=0;
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nPedido = new javax.swing.JTextField();
        mostrarjButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla2 = new javax.swing.JTable();
        enviarjButton2 = new javax.swing.JButton();
        mesg = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mostrarjButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mostrarjButton1.setText("Mostrar");
        mostrarjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarjButton1ActionPerformed(evt);
            }
        });

        tabla2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descripcion", "Ancho", "Alto", "Largo", "Cantidad"
            }
        ));
        jScrollPane2.setViewportView(tabla2);

        jScrollPane1.setViewportView(jScrollPane2);

        enviarjButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        enviarjButton2.setText("Enviar");
        enviarjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarjButton2ActionPerformed(evt);
            }
        });

        mesg.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        mesg.setForeground(new java.awt.Color(102, 255, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("ENVIOS");

        jLabel2.setText("Nº de Pedido");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(150, 150, 150)
                            .addComponent(jLabel2)
                            .addGap(52, 52, 52)
                            .addComponent(nPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(mostrarjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(enviarjButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(21, 21, 21)
                                    .addComponent(mesg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(jLabel1)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mostrarjButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nPedido)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(enviarjButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(mesg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(327, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarjButton1ActionPerformed
         Clicks++;
         String [] col={"Descripcion","Ancho","Alto","Largo","Cantidad"};
         mesg.setText("");
         DefaultTableModel model=(DefaultTableModel)tabla2.getModel();
         
        DatosProductos d=new DatosProductos();
        id=nPedido.getText();
        if(nPedido.getText().equals("")) {   
            mesg.setText("Introduce un nº de Pedido");
            mesg.setForeground(Color.red);
            return; 
        }
        
        List<DatosProductos> ls=d.recogerPedidoProducto(nPedido.getText());
        
        if(ls.size()==0){
            mesg.setText("No hay datos");
            mesg.setForeground(Color.red);
            return;  
        }
        
        Object arr[][]=new Object[ls.size()][];
        for(int j=0; j<ls.size(); j++){
            arr[j]=new Object[5];
        }
        for(int i=0; i<ls.size(); i++){            
                arr[i][0]=ls.get(i).descripcion;
                arr[i][1]=ls.get(i).ancho;
                arr[i][2]=ls.get(i).alto;
                arr[i][3]=ls.get(i).largo;
                arr[i][4]=ls.get(i).cantidad;
                   
        }
        
        model.setDataVector(arr, col);
    }//GEN-LAST:event_mostrarjButton1ActionPerformed
     
    private void enviarjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarjButton2ActionPerformed
          mesg.setText("");
          if(id.equals("")){
            mesg.setText("Introduce un nº de Pedido");
            mesg.setForeground(Color.red);
          }else {
              
            if(!hayID(id)){    
                DatosProductos d=new DatosProductos();
                 d.EscribirEnvios(id, "Enviado");
                 mesg.setText("Enviado correctamente");
                 mesg.setForeground(Color.GREEN);
            }else {
                mesg.setText("Este pedido ya ha sido enviado");
            mesg.setForeground(Color.red);
            }
          }

    }//GEN-LAST:event_enviarjButton2ActionPerformed
     public boolean hayID(String d){
        String NombreFichero="Envios.txt";
        BufferedReader br = null;
        try {
            br = new BufferedReader(new FileReader(NombreFichero));
            String linea;
            while ((linea = br.readLine()) != null) {
                String [] arr=linea.split(":");
                if(!linea.equals("")){     
                     if((arr[0].replace(" ","")).equals(d)){    
                         return true;
                     }
                }
            }
        } catch (IOException e) {
        
        } finally {
            try {
                if (br != null) {
                    br.close();
                }
            } catch (IOException ex) {
        
            }
        }
         
         return false;
     }


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Envios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Envios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Envios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Envios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Envios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enviarjButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Label mesg;
    private javax.swing.JButton mostrarjButton1;
    private javax.swing.JTextField nPedido;
    private javax.swing.JTable tabla2;
    // End of variables declaration//GEN-END:variables
}
