/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofint1;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

public class Productos extends javax.swing.JFrame {

    public  List<DatosEmbalajes> embjDatos ;
    public Productos() 
    {   
        setLocation(300, 100);
        embjDatos=new ArrayList();
        LeerDatosEmbalajes();
        
        initComponents();
    }
    private void LeerDatosEmbalajes()
    {   String NombreFichero="Embalajes.txt";
        BufferedReader br = null;
        try {
            br = new BufferedReader(new FileReader(NombreFichero));
            String linea; 
            while ((linea = br.readLine()) != null) {
                DatosEmbalajes d=new DatosEmbalajes();
                
                String [] arr=linea.split(":");
                if(!linea.equals(""))
                {    d.ancho=Integer.parseInt(arr[0].replace(" ", ""));
                    d.largo=Integer.parseInt(arr[1].replace(" ",""));
                    d.alto=Integer.parseInt(arr[2].replace(" ",""));
                    embjDatos.add(d);  
                }
            }
        } catch (IOException e) {
        
        } finally {
            try {
                if (br != null) {
                    br.close();
                }
            } catch (IOException ex) {
        
            }
        }
         
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Descripcion = new javax.swing.JTextField();
        Ancho = new javax.swing.JTextField();
        Alto = new javax.swing.JTextField();
        Largo = new javax.swing.JTextField();
        button1 = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Descripcion.setText(" ");

        Ancho.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Ancho.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AnchoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                AnchoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AnchoKeyTyped(evt);
            }
        });

        Alto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AltoActionPerformed(evt);
            }
        });
        Alto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AltoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                AltoKeyReleased(evt);
            }
        });

        Largo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LargoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                LargoKeyReleased(evt);
            }
        });

        button1.setBackground(new java.awt.Color(255, 255, 255));
        button1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button1.setLabel("Guardar");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveData(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("PRODUCTOS");

        jLabel3.setText("Descripcion");

        jLabel4.setText("Ancho");

        jLabel5.setText("Alto");

        jLabel6.setText("Largo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(189, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Ancho, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(66, 81, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Alto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Largo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(93, 93, 93))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel2)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ancho, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Alto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Largo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Descripcion.getAccessibleContext().setAccessibleName("Description");
        Ancho.getAccessibleContext().setAccessibleName("Width");
        jLabel1.getAccessibleContext().setAccessibleName("Label5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveData(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveData
         if (Descripcion.getText().equals("") ||  Largo.getText().equals("") || Alto.getText().equals("") || Ancho.getText().equals("") )
        {
            jLabel1.setText("Rellena todos los campos");            
            jLabel1.setForeground(Color.red);
        }
        else 
        {
             DatosProductos d=new DatosProductos();
             d.descripcion=Descripcion.getText();
             d.alto=Integer.parseInt(Alto.getText());
             d.largo=Integer.parseInt(Largo.getText());
             d.ancho=Integer.parseInt(Ancho.getText());
             if(HayCaja(d))
             {
                d.escribirEnFichero();
                jLabel1.setText("Añadido correctamente");
                jLabel1.setForeground(Color.GREEN);
                Alto.setText("");
                Largo.setText("");
                Ancho.setText("");
                Descripcion.setText("");
             }
             else 
             {
                 jLabel1.setText("No hay cajas");
                jLabel1.setForeground(Color.red);
             }
        }
        
    }//GEN-LAST:event_SaveData
     private  boolean HayCaja(DatosProductos d){
         
         for (int i=0; i<embjDatos.size(); i++){
             if(d.ancho<=embjDatos.get(i).ancho && d.alto<=embjDatos.get(i).alto && d.largo<=embjDatos.get(i).largo ) {
                 
                 return  true;
             }         
        }
         return false;
     }
             
    private void AnchoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AnchoKeyPressed
        
        int key=evt.getKeyCode();
        if ((key>=evt.VK_0 && key<=evt.VK_9) || key==evt.VK_BACK_SPACE) {
           Ancho.setEditable(true);
           Ancho.setBackground(Color.GREEN); 
           
        }
        else {
            Ancho.setEditable(false);
            Ancho.setBackground(Color.red);
            jLabel1.setText("Introduce sólo números");
        }
    }//GEN-LAST:event_AnchoKeyPressed

    private void AltoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AltoActionPerformed
        
    }//GEN-LAST:event_AltoActionPerformed

    private void AltoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AltoKeyPressed
        int key=evt.getKeyCode();
        if ((key>=evt.VK_0 && key<=evt.VK_9) || key==evt.VK_BACK_SPACE) {
           Alto.setEditable(true);
           Alto.setBackground(Color.GREEN); 
           jLabel1.setText("");
        }
        else {
            Alto.setEditable(false);
            Alto.setBackground(Color.red);
            jLabel1.setText("Introduce sólo números");
        }
    }//GEN-LAST:event_AltoKeyPressed

    private void LargoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LargoKeyPressed
         int key=evt.getKeyCode();
        if ((key>=evt.VK_0 && key<=evt.VK_9) || key==evt.VK_BACK_SPACE) {
           Largo.setEditable(true);
           Largo.setBackground(Color.GREEN); 
           jLabel1.setText("");
        }
        else {
            Largo.setEditable(false);
            Largo.setBackground(Color.red);
            jLabel1.setText("Introduce sólo números");
        }
    }//GEN-LAST:event_LargoKeyPressed
    
    private void AnchoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AnchoKeyTyped
        
    }//GEN-LAST:event_AnchoKeyTyped

    private void AnchoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AnchoKeyReleased
           int vl=1;
           try {
           vl=Integer.parseInt(Ancho.getText());
           }
           catch (Exception e){
               
           }
            
           if(vl>0 && vl<=20){
               Ancho.setBackground(Color.GREEN);
               jLabel1.setText("");
           }
           else {  
               Ancho.setBackground(Color.red);
               jLabel1.setText("El límite es 20");
           }       
    }//GEN-LAST:event_AnchoKeyReleased

    private void AltoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AltoKeyReleased
       int vl=1;
           try  {
           vl=Integer.parseInt(Alto.getText());
           }catch (Exception e){
               
           }
            
           if(vl>0 && vl<=30){
               Alto.setBackground(Color.GREEN);
               jLabel1.setText("");
           }
           else {  
               Alto.setBackground(Color.red);
               jLabel1.setText("El límite es 30");
           } 
    }//GEN-LAST:event_AltoKeyReleased

    private void LargoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LargoKeyReleased
       int vl=1;
           try {
           vl=Integer.parseInt(Largo.getText());
           }
           catch (Exception e){
               
           }
            
           if(vl>0 && vl<=20){
               Largo.setBackground(Color.GREEN);
               jLabel1.setText("");
           }
           else {  
               Largo.setBackground(Color.red);
               jLabel1.setText("El límite es 20");
           }
    }//GEN-LAST:event_LargoKeyReleased
     
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Productos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Alto;
    private javax.swing.JTextField Ancho;
    private javax.swing.JTextField Descripcion;
    private javax.swing.JTextField Largo;
    private java.awt.Button button1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
